# Generated by Django 4.1.4 on 2022-12-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=19)),
                ('medida', models.CharField(max_length=3)),
                ('fecha_entrada', models.DateField(auto_now=True)),
            ],
        ),
    ]
